### ISSUE TITLE
flutter runでエミュレーションできないよ😭

### ISSUE THREAD

**Issue by feynman1729** [giant-shrimp/Chikuhou_frontend#5]
まずgitの操作を行う。
```bash
git clone git@github.com:giant-shrimp/Chikuhou_frontend.git

git branch feature/design

git switch feature/design

git pull origin feature/design
```
この後に
```bash
flutter clean
flutter pub get
flutter run
```
と行ったが
`.dart_tool/flutter_gen/gen_l10n/app_localizations.dart`が見つからないと怒られた。
AppLocalizationsが正しく設定されていないことが理由として考えられるが、ローカライゼーションファイルl10nが生成されてるにも関わらずエラー吐いてる。

**Comment by giant-shrimp** [comment]
コマンドで
flutter pub get
flutter gen-l10n
flutter run
を試してみてください。

**Comment by feynman1729** [comment]
![image](https://github.com/user-attachments/assets/c3a36e22-6956-4a42-8eb8-d0106961a039)
無事解決しました🥰🙏😘👍
